[package]
name = "canapi"
version = "0.2.0"
authors = ["Bat' <baptiste@gelez.xyz>"]
description = "Define REST APIs and share them between client and server"
license = "AGPL-3.0"

[dependencies]
serde = "1.0"
